import { drizzleZeroConfig } from "drizzle-zero";
import * as schema from "./src/db/schema.ts";

export default drizzleZeroConfig(schema, {
	tables: {
		user: { id: true, name: true, image: true },
		workspace: { id: true, name: true, ownerId: true, kind: true },
		membership: { id: true, userId: true, workspaceId: true, role: true },
		list: {
			id: true,
			workspaceId: true,
			ownerId: true,
			title: true,
			kind: true,
			icon: true,
			folderId: true,
			sortKey: true,
			completedDisplay: true,
		},
		task: {
			id: true,
			listId: true,
			title: true,
			done: true,
			notes: true,
			dueAt: true,
			dueAllDay: true,
			priority: true,
			completedAt: true,
			sortKey: true,
			parentId: true,
			quantity: true,
			unit: true,
			category: true,
			rrule: true,
			recurrenceRelative: true,
			reminderTime: true,
		},
		folder: { id: true, workspaceId: true, name: true, sortKey: true },
		label: { id: true, workspaceId: true, name: true, color: true },
		taskLabel: { id: true, taskId: true, labelId: true },
		template: {
			id: true,
			workspaceId: true,
			kind: true,
			name: true,
			icon: true,
			content: true,
			createdBy: true,
		},
		invite: {
			id: true,
			workspaceId: true,
			role: true,
			email: true,
			// token intentionally NOT exposed (redeem secret; server-only)
			status: true,
			expiresAt: true,
			maxUses: true,
			uses: true,
			attachTaskId: true,
			attachKind: true,
			createdBy: true,
			createdAt: true,
		},
		taskAssignee: { id: true, taskId: true, userId: true },
		comment: {
			id: true,
			taskId: true,
			authorId: true,
			body: true,
			createdAt: true,
			editedAt: true,
		},
		managedAccount: {
			id: true,
			userId: true,
			guardianId: true,
			restricted: true,
			createdAt: true,
		},
		view: {
			id: true,
			ownerId: true,
			workspaceId: true,
			name: true,
			icon: true,
			scope: true,
			filter: true,
			display: true,
			sortKey: true,
			createdAt: true,
			updatedAt: true,
		},
		userPref: {
			id: true,
			keymap: true,
			keymapProfile: true,
			homeViewRef: true,
			pinnedViews: true,
			createdAt: true,
			updatedAt: true,
		},
		habitLog: {
			id: true,
			habitId: true,
			date: true,
			status: true,
			completedAt: true,
			createdAt: true,
		},
		karma: {
			userId: true,
			points: true,
			level: true,
			updatedAt: true,
		},
		karmaEvent: {
			id: true,
			userId: true,
			date: true,
			delta: true,
			reason: true,
			createdAt: true,
		},
		focusSession: {
			id: true,
			userId: true,
			taskId: true,
			kind: true,
			startedAt: true,
			endedAt: true,
			durationSec: true,
			createdAt: true,
		},
	},
});
