import { drizzleZeroConfig } from "drizzle-zero";
import * as schema from "./src/db/schema.ts";

export default drizzleZeroConfig(schema, {
	tables: {
		user: { id: true, name: true, image: true },
		workspace: {
			id: true,
			name: true,
			ownerId: true,
			kind: true,
			rotationRequired: true,
		},
		membership: { id: true, userId: true, workspaceId: true, role: true },
		list: {
			id: true,
			workspaceId: true,
			ownerId: true,
			title: true,
			kind: true,
			icon: true,
			folderId: true,
			sortKey: true,
			completedDisplay: true,
		},
		task: {
			id: true,
			listId: true,
			title: true,
			done: true,
			notes: true,
			dueAt: true,
			dueAllDay: true,
			priority: true,
			completedAt: true,
			sortKey: true,
			parentId: true,
			quantity: true,
			unit: true,
			category: true,
			rrule: true,
			recurrenceRelative: true,
			reminderTime: true,
			repeatEveryMin: true,
			maxRepeats: true,
			fallbackUserId: true,
			urgent: true,
		},
		folder: { id: true, workspaceId: true, name: true, sortKey: true },
		label: { id: true, workspaceId: true, name: true, color: true },
		taskLabel: { id: true, taskId: true, labelId: true },
		template: {
			id: true,
			workspaceId: true,
			kind: true,
			name: true,
			icon: true,
			content: true,
			createdBy: true,
		},
		invite: {
			id: true,
			workspaceId: true,
			role: true,
			email: true,
			// token intentionally NOT exposed (redeem secret; server-only)
			status: true,
			expiresAt: true,
			maxUses: true,
			uses: true,
			// A claimed fast-path invite is already past the revocation boundary,
			// even though token consumption waits for its durable WDK grant.
			claimedBy: true,
			attachTaskId: true,
			attachKind: true,
			createdBy: true,
			createdAt: true,
		},
		taskAssignee: { id: true, taskId: true, userId: true },
		comment: {
			id: true,
			taskId: true,
			authorId: true,
			body: true,
			createdAt: true,
			editedAt: true,
		},
		managedAccount: {
			id: true,
			userId: true,
			guardianId: true,
			restricted: true,
			createdAt: true,
		},
		view: {
			id: true,
			ownerId: true,
			workspaceId: true,
			name: true,
			icon: true,
			scope: true,
			filter: true,
			display: true,
			sortKey: true,
			createdAt: true,
			updatedAt: true,
		},
		userPref: {
			id: true,
			keymap: true,
			keymapProfile: true,
			homeViewRef: true,
			pinnedViews: true,
			karmaGoals: true,
			vacation: true,
			focus: true,
			timezone: true,
			quietHours: true,
			escalationDefaults: true,
			locale: true,
			theme: true,
			e2eAutoLockMinutes: true,
			createdAt: true,
			updatedAt: true,
		},
		habitLog: {
			id: true,
			habitId: true,
			date: true,
			status: true,
			karmaDelta: true,
			completedAt: true,
			createdAt: true,
		},
		karma: {
			userId: true,
			points: true,
			level: true,
			updatedAt: true,
		},
		karmaEvent: {
			id: true,
			userId: true,
			date: true,
			delta: true,
			reason: true,
			createdAt: true,
		},
		dashboard: {
			id: true,
			ownerId: true,
			workspaceId: true,
			scope: true,
			name: true,
			icon: true,
			panels: true,
			sortKey: true,
			createdAt: true,
			updatedAt: true,
		},
		focusSession: {
			id: true,
			userId: true,
			taskId: true,
			kind: true,
			startedAt: true,
			endedAt: true,
			durationSec: true,
			createdAt: true,
		},
		notificationChannel: {
			id: true,
			userId: true,
			kind: true,
			// config intentionally NOT exposed (channel credentials; server-only)
			enabled: true,
			verifiedAt: true,
			// Health, not diagnostics: a closed enum plus a timestamp. The raw
			// provider error stays in delivery_attempt (server-only, redacted).
			ackVerifiedAt: true,
			lastErrorAt: true,
			lastErrorCode: true,
			createdAt: true,
			updatedAt: true,
		},
		reminderState: {
			id: true,
			taskId: true,
			occurrenceAt: true,
			recipientUserId: true,
			status: true,
			fireCount: true,
			// Synced so the in-app ack can clear it exactly as the capability
			// route does; without it the two ack paths leave different rows.
			nextAttemptAt: true,
			deferredUntil: true,
			firedLate: true,
			ackedAt: true,
			ackedVia: true,
			ackOutcome: true,
			createdAt: true,
		},
	},
});
