apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ditero-zero
  namespace: ditero
  labels:
    app.kubernetes.io/name: ditero
    app.kubernetes.io/instance: ditero
    app.kubernetes.io/version: 0.0.1-alpha.5
    app.kubernetes.io/part-of: ditero
    app.kubernetes.io/component: zero
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
