apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ditero
resources:
- ditero-app-deployment.yaml
- ditero-app-persistentvolumeclaim.yaml
- ditero-app-service.yaml
- ditero-zero-deployment.yaml
- ditero-zero-persistentvolumeclaim.yaml
- ditero-zero-service.yaml
- namespace.yaml
configMapGenerator:
- name: ditero-app-config
  envs:
  - app.env
configurations:
- name-reference.yaml
