apiVersion: v2
name: ditero
description: Ditero web application and Zero sync server with external PostgreSQL
type: application
version: 0.0.1-alpha.1
appVersion: "0.0.1-alpha.1"
home: https://github.com/iuliandita/ditero
sources:
  - https://github.com/iuliandita/ditero
