// @generated drizzle-zero signature:sha256:5ffe9c0ed5c1edd020a8386c79d17bf380b2fed252b4af8b32c770aea627ee9c
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const commentTable = {
    "name": "comment",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "taskId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "task_id"
        },
        "authorId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "author_id"
        },
        "body": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "editedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "edited_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const dashboardTable = {
    "name": "dashboard",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "workspaceId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "scope": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "workspace" | "personal"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "icon": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "panels": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const focusSessionTable = {
    "name": "focusSession",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "taskId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "task_id"
        },
        "kind": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "work" | "break"
        },
        "startedAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "started_at"
        },
        "endedAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "ended_at"
        },
        "durationSec": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "duration_sec"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "focus_session"
} as const;
const folderTable = {
    "name": "folder",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        }
    },
    "primaryKey": ["id"]
} as const;
const habitLogTable = {
    "name": "habitLog",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "habitId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "habit_id"
        },
        "date": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "done" | "skipped"
        },
        "karmaDelta": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "karma_delta"
        },
        "completedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "completed_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "habit_log"
} as const;
const inviteTable = {
    "name": "invite",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "owner" | "admin" | "member" | "viewer"
        },
        "email": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "pending" | "accepted" | "revoked"
        },
        "expiresAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "expires_at"
        },
        "maxUses": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "max_uses"
        },
        "uses": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "attachTaskId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "attach_task_id"
        },
        "attachKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "assign" | "mention",
            "serverName": "attach_kind"
        },
        "createdBy": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "created_by"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const karmaTable = {
    "name": "karma",
    "columns": {
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "points": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "level": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["userId"]
} as const;
const karmaEventTable = {
    "name": "karmaEvent",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "date": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "delta": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "reason": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "karma_event"
} as const;
const labelTable = {
    "name": "label",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "color": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const listTable = {
    "name": "list",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "kind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "tasks" | "shopping" | "checklist" | "project" | "habits"
        },
        "icon": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "folderId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "folder_id"
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        },
        "completedDisplay": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "sink" | "keep" | "hide",
            "serverName": "completed_display"
        }
    },
    "primaryKey": ["id"]
} as const;
const managedAccountTable = {
    "name": "managedAccount",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "guardianId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "guardian_id"
        },
        "restricted": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "managed_account"
} as const;
const membershipTable = {
    "name": "membership",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "owner" | "admin" | "member" | "viewer"
        }
    },
    "primaryKey": ["id"]
} as const;
const taskTable = {
    "name": "task",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "listId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "list_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "done": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "notes": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "dueAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "due_at"
        },
        "dueAllDay": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "due_all_day"
        },
        "priority": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "completedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "completed_at"
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        },
        "parentId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "parent_id"
        },
        "quantity": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "unit": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "category": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "rrule": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "recurrenceRelative": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "recurrence_relative"
        },
        "reminderTime": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "reminder_time"
        }
    },
    "primaryKey": ["id"]
} as const;
const taskAssigneeTable = {
    "name": "taskAssignee",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "taskId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "task_id"
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        }
    },
    "primaryKey": ["id"],
    "serverName": "task_assignee"
} as const;
const taskLabelTable = {
    "name": "taskLabel",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "taskId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "task_id"
        },
        "labelId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "label_id"
        }
    },
    "primaryKey": ["id"],
    "serverName": "task_label"
} as const;
const templateTable = {
    "name": "template",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "kind": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "list" | "task"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "icon": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "content": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "createdBy": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "created_by"
        }
    },
    "primaryKey": ["id"]
} as const;
const userTable = {
    "name": "user",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "image": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const userPrefTable = {
    "name": "userPref",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "keymap": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "keymapProfile": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "default" | "vim",
            "serverName": "keymap_profile"
        },
        "homeViewRef": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "home_view_ref"
        },
        "pinnedViews": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as ReadonlyJSONValue,
            "serverName": "pinned_views"
        },
        "karmaGoals": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as ReadonlyJSONValue,
            "serverName": "karma_goals"
        },
        "vacation": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "focus": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "user_pref"
} as const;
const viewTable = {
    "name": "view",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "workspaceId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "icon": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "scope": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "workspace" | "personal"
        },
        "filter": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "display": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const workspaceTable = {
    "name": "workspace",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "kind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "personal" | "shared"
        }
    },
    "primaryKey": ["id"]
} as const;
const commentRelationships = {
    "task": [{ "sourceField": ["taskId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }],
    "author": [{ "sourceField": ["authorId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const dashboardRelationships = {
    "owner": [{ "sourceField": ["ownerId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const focusSessionRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "task": [{ "sourceField": ["taskId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }]
} as const;
const folderRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }],
    "lists": [{ "sourceField": ["id"], "destField": ["folderId"], "destSchema": "list", "cardinality": "many" }]
} as const;
const habitLogRelationships = {
    "habit": [{ "sourceField": ["habitId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }]
} as const;
const inviteRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const karmaEventRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const karmaRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const labelRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }],
    "taskLabels": [{ "sourceField": ["id"], "destField": ["labelId"], "destSchema": "taskLabel", "cardinality": "many" }]
} as const;
const listRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }],
    "folder": [{ "sourceField": ["folderId"], "destField": ["id"], "destSchema": "folder", "cardinality": "one" }],
    "tasks": [{ "sourceField": ["id"], "destField": ["listId"], "destSchema": "task", "cardinality": "many" }]
} as const;
const managedAccountRelationships = {
    "account": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "guardian": [{ "sourceField": ["guardianId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const membershipRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const taskAssigneeRelationships = {
    "task": [{ "sourceField": ["taskId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }],
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const taskLabelRelationships = {
    "task": [{ "sourceField": ["taskId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }],
    "label": [{ "sourceField": ["labelId"], "destField": ["id"], "destSchema": "label", "cardinality": "one" }]
} as const;
const taskRelationships = {
    "list": [{ "sourceField": ["listId"], "destField": ["id"], "destSchema": "list", "cardinality": "one" }],
    "parent": [{ "sourceField": ["parentId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }],
    "subtasks": [{ "sourceField": ["id"], "destField": ["parentId"], "destSchema": "task", "cardinality": "many" }],
    "taskLabels": [{ "sourceField": ["id"], "destField": ["taskId"], "destSchema": "taskLabel", "cardinality": "many" }],
    "assignees": [{ "sourceField": ["id"], "destField": ["taskId"], "destSchema": "taskAssignee", "cardinality": "many" }],
    "comments": [{ "sourceField": ["id"], "destField": ["taskId"], "destSchema": "comment", "cardinality": "many" }],
    "habitLogs": [{ "sourceField": ["id"], "destField": ["habitId"], "destSchema": "habitLog", "cardinality": "many" }],
    "focusSessions": [{ "sourceField": ["id"], "destField": ["taskId"], "destSchema": "focusSession", "cardinality": "many" }]
} as const;
const templateRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const userRelationships = {
    "memberships": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "membership", "cardinality": "many" }]
} as const;
const userPrefRelationships = {
    "user": [{ "sourceField": ["id"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const viewRelationships = {
    "owner": [{ "sourceField": ["ownerId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const workspaceRelationships = {
    "memberships": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "membership", "cardinality": "many" }],
    "lists": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "list", "cardinality": "many" }],
    "folders": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "folder", "cardinality": "many" }],
    "labels": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "label", "cardinality": "many" }],
    "templates": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "template", "cardinality": "many" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "comment": commentTable,
        "dashboard": dashboardTable,
        "focusSession": focusSessionTable,
        "folder": folderTable,
        "habitLog": habitLogTable,
        "invite": inviteTable,
        "karma": karmaTable,
        "karmaEvent": karmaEventTable,
        "label": labelTable,
        "list": listTable,
        "managedAccount": managedAccountTable,
        "membership": membershipTable,
        "task": taskTable,
        "taskAssignee": taskAssigneeTable,
        "taskLabel": taskLabelTable,
        "template": templateTable,
        "user": userTable,
        "userPref": userPrefTable,
        "view": viewTable,
        "workspace": workspaceTable
    },
    "relationships": {
        "comment": commentRelationships,
        "dashboard": dashboardRelationships,
        "focusSession": focusSessionRelationships,
        "folder": folderRelationships,
        "habitLog": habitLogRelationships,
        "invite": inviteRelationships,
        "karmaEvent": karmaEventRelationships,
        "karma": karmaRelationships,
        "label": labelRelationships,
        "list": listRelationships,
        "managedAccount": managedAccountRelationships,
        "membership": membershipRelationships,
        "taskAssignee": taskAssigneeRelationships,
        "taskLabel": taskLabelRelationships,
        "task": taskRelationships,
        "template": templateRelationships,
        "user": userRelationships,
        "userPref": userPrefRelationships,
        "view": viewRelationships,
        "workspace": workspaceRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "comment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Comment = Row<(typeof schema)["tables"]["comment"]>;
/**
 * Represents a row from the "dashboard" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Dashboard = Row<(typeof schema)["tables"]["dashboard"]>;
/**
 * Represents a row from the "focusSession" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FocusSession = Row<(typeof schema)["tables"]["focusSession"]>;
/**
 * Represents a row from the "folder" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Folder = Row<(typeof schema)["tables"]["folder"]>;
/**
 * Represents a row from the "habitLog" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type HabitLog = Row<(typeof schema)["tables"]["habitLog"]>;
/**
 * Represents a row from the "invite" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invite = Row<(typeof schema)["tables"]["invite"]>;
/**
 * Represents a row from the "karma" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Karma = Row<(typeof schema)["tables"]["karma"]>;
/**
 * Represents a row from the "karmaEvent" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type KarmaEvent = Row<(typeof schema)["tables"]["karmaEvent"]>;
/**
 * Represents a row from the "label" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Label = Row<(typeof schema)["tables"]["label"]>;
/**
 * Represents a row from the "list" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type List = Row<(typeof schema)["tables"]["list"]>;
/**
 * Represents a row from the "managedAccount" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ManagedAccount = Row<(typeof schema)["tables"]["managedAccount"]>;
/**
 * Represents a row from the "membership" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Membership = Row<(typeof schema)["tables"]["membership"]>;
/**
 * Represents a row from the "task" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<(typeof schema)["tables"]["task"]>;
/**
 * Represents a row from the "taskAssignee" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TaskAssignee = Row<(typeof schema)["tables"]["taskAssignee"]>;
/**
 * Represents a row from the "taskLabel" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TaskLabel = Row<(typeof schema)["tables"]["taskLabel"]>;
/**
 * Represents a row from the "template" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Template = Row<(typeof schema)["tables"]["template"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "userPref" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserPref = Row<(typeof schema)["tables"]["userPref"]>;
/**
 * Represents a row from the "view" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type View = Row<(typeof schema)["tables"]["view"]>;
/**
 * Represents a row from the "workspace" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspace"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
