// @generated drizzle-zero signature:sha256:e618c77d55abbba9230bb094cd02e55048e2e4229b792bac388622990ef753ca
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const folderTable = {
    "name": "folder",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        }
    },
    "primaryKey": ["id"]
} as const;
const labelTable = {
    "name": "label",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "color": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const listTable = {
    "name": "list",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "kind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "tasks" | "shopping" | "checklist" | "project" | "habits"
        },
        "icon": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "folderId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "folder_id"
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        },
        "completedDisplay": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "sink" | "keep" | "hide",
            "serverName": "completed_display"
        }
    },
    "primaryKey": ["id"]
} as const;
const membershipTable = {
    "name": "membership",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "owner" | "admin" | "member" | "viewer"
        }
    },
    "primaryKey": ["id"]
} as const;
const taskTable = {
    "name": "task",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "listId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "list_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "done": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "notes": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "dueAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "due_at"
        },
        "dueAllDay": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "due_all_day"
        },
        "priority": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "completedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "completed_at"
        },
        "sortKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sort_key"
        },
        "parentId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "parent_id"
        },
        "quantity": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "unit": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "category": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const taskLabelTable = {
    "name": "taskLabel",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "taskId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "task_id"
        },
        "labelId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "label_id"
        }
    },
    "primaryKey": ["id"],
    "serverName": "task_label"
} as const;
const templateTable = {
    "name": "template",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "kind": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "list" | "task"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "icon": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "content": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as ReadonlyJSONValue
        },
        "createdBy": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "created_by"
        }
    },
    "primaryKey": ["id"]
} as const;
const userTable = {
    "name": "user",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "image": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const workspaceTable = {
    "name": "workspace",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "kind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "personal" | "shared"
        }
    },
    "primaryKey": ["id"]
} as const;
const folderRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }],
    "lists": [{ "sourceField": ["id"], "destField": ["folderId"], "destSchema": "list", "cardinality": "many" }]
} as const;
const labelRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }],
    "taskLabels": [{ "sourceField": ["id"], "destField": ["labelId"], "destSchema": "taskLabel", "cardinality": "many" }]
} as const;
const listRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }],
    "folder": [{ "sourceField": ["folderId"], "destField": ["id"], "destSchema": "folder", "cardinality": "one" }],
    "tasks": [{ "sourceField": ["id"], "destField": ["listId"], "destSchema": "task", "cardinality": "many" }]
} as const;
const membershipRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const taskLabelRelationships = {
    "task": [{ "sourceField": ["taskId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }],
    "label": [{ "sourceField": ["labelId"], "destField": ["id"], "destSchema": "label", "cardinality": "one" }]
} as const;
const taskRelationships = {
    "list": [{ "sourceField": ["listId"], "destField": ["id"], "destSchema": "list", "cardinality": "one" }],
    "parent": [{ "sourceField": ["parentId"], "destField": ["id"], "destSchema": "task", "cardinality": "one" }],
    "subtasks": [{ "sourceField": ["id"], "destField": ["parentId"], "destSchema": "task", "cardinality": "many" }],
    "taskLabels": [{ "sourceField": ["id"], "destField": ["taskId"], "destSchema": "taskLabel", "cardinality": "many" }]
} as const;
const templateRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const userRelationships = {
    "memberships": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "membership", "cardinality": "many" }]
} as const;
const workspaceRelationships = {
    "memberships": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "membership", "cardinality": "many" }],
    "lists": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "list", "cardinality": "many" }],
    "folders": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "folder", "cardinality": "many" }],
    "labels": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "label", "cardinality": "many" }],
    "templates": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "template", "cardinality": "many" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "folder": folderTable,
        "label": labelTable,
        "list": listTable,
        "membership": membershipTable,
        "task": taskTable,
        "taskLabel": taskLabelTable,
        "template": templateTable,
        "user": userTable,
        "workspace": workspaceTable
    },
    "relationships": {
        "folder": folderRelationships,
        "label": labelRelationships,
        "list": listRelationships,
        "membership": membershipRelationships,
        "taskLabel": taskLabelRelationships,
        "task": taskRelationships,
        "template": templateRelationships,
        "user": userRelationships,
        "workspace": workspaceRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "folder" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Folder = Row<(typeof schema)["tables"]["folder"]>;
/**
 * Represents a row from the "label" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Label = Row<(typeof schema)["tables"]["label"]>;
/**
 * Represents a row from the "list" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type List = Row<(typeof schema)["tables"]["list"]>;
/**
 * Represents a row from the "membership" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Membership = Row<(typeof schema)["tables"]["membership"]>;
/**
 * Represents a row from the "task" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<(typeof schema)["tables"]["task"]>;
/**
 * Represents a row from the "taskLabel" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TaskLabel = Row<(typeof schema)["tables"]["taskLabel"]>;
/**
 * Represents a row from the "template" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Template = Row<(typeof schema)["tables"]["template"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "workspace" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspace"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
