// @generated drizzle-zero signature:sha256:1207c1c3f0fc1fd9c3b036e5e0748858519cd65bb45183c736d448104adf8fa5
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const listTable = {
    "name": "list",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const membershipTable = {
    "name": "membership",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "owner" | "admin" | "member" | "viewer"
        }
    },
    "primaryKey": ["id"]
} as const;
const taskTable = {
    "name": "task",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "listId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "list_id"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "done": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        }
    },
    "primaryKey": ["id"]
} as const;
const userTable = {
    "name": "user",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "image": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"]
} as const;
const workspaceTable = {
    "name": "workspace",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "ownerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "owner_id"
        },
        "kind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "personal" | "shared"
        }
    },
    "primaryKey": ["id"]
} as const;
const listRelationships = {
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }],
    "tasks": [{ "sourceField": ["id"], "destField": ["listId"], "destSchema": "task", "cardinality": "many" }]
} as const;
const membershipRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "workspace": [{ "sourceField": ["workspaceId"], "destField": ["id"], "destSchema": "workspace", "cardinality": "one" }]
} as const;
const taskRelationships = {
    "list": [{ "sourceField": ["listId"], "destField": ["id"], "destSchema": "list", "cardinality": "one" }]
} as const;
const userRelationships = {
    "memberships": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "membership", "cardinality": "many" }]
} as const;
const workspaceRelationships = {
    "memberships": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "membership", "cardinality": "many" }],
    "lists": [{ "sourceField": ["id"], "destField": ["workspaceId"], "destSchema": "list", "cardinality": "many" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "list": listTable,
        "membership": membershipTable,
        "task": taskTable,
        "user": userTable,
        "workspace": workspaceTable
    },
    "relationships": {
        "list": listRelationships,
        "membership": membershipRelationships,
        "task": taskRelationships,
        "user": userRelationships,
        "workspace": workspaceRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "list" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type List = Row<(typeof schema)["tables"]["list"]>;
/**
 * Represents a row from the "membership" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Membership = Row<(typeof schema)["tables"]["membership"]>;
/**
 * Represents a row from the "task" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<(typeof schema)["tables"]["task"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "workspace" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspace"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
