allowBuilds:
  '@rocicorp/zero-sqlite3': true
  esbuild: true
  protobufjs: true
patchedDependencies:
  postgres@3.4.7: patches/postgres@3.4.7.patch
overrides:
  fastify: 5.12.3
  '@opentelemetry/core@2.7.1': 2.8.0
  '@opentelemetry/propagator-jaeger@2.7.1': 2.9.0
  'fast-uri@3.1.5': 3.1.6
  'fast-uri@4.1.2': 4.1.3
