apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ditero
resources:
- ../base
- cluster.yaml
configMapGenerator:
- name: ditero-db-bootstrap
  files:
  - roles.sql
configurations:
- name-reference.yaml
