CREATE ROLE ditero_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE ditero_zero NOLOGIN SUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT REPLICATION;
ALTER SCHEMA public OWNER TO ditero_migrator;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE ditero TO ditero_runtime, ditero_zero;
GRANT USAGE ON SCHEMA public TO ditero_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ditero_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ditero_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ditero_migrator IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ditero_runtime;
CREATE SCHEMA zero_0 AUTHORIZATION ditero_zero;
GRANT USAGE ON SCHEMA zero_0 TO ditero_runtime, ditero_migrator;
ALTER DEFAULT PRIVILEGES FOR ROLE ditero_zero IN SCHEMA zero_0
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ditero_runtime, ditero_migrator;
ALTER DEFAULT PRIVILEGES FOR ROLE ditero_zero IN SCHEMA zero_0
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ditero_runtime, ditero_migrator;
